bump

diff --git a/.github/actions/download_artifact/action.yml b/.github/actions/download_artifact/action.yml
--- a/.github/actions/download_artifact/action.yml
+++ b/.github/actions/download_artifact/action.yml
@@ -22,12 +22,13 @@ runs:
 
     - name: "Get artifact"
       run: |
-          mkdir -p $PATH && cd $PATH
-          ART_ID=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts \
-            --jq '.artifacts[] | select(.name=="$ARTIFACT_NAME") | .id')
-          if [ -z "$ART_ID" ]; then
-            echo "Artifact $ARTIFACT_NAME not found in run $RUN_ID" >&2
-            exit 1
+        ls -la
+        mkdir -p $PATH && cd $PATH
+        ART_ID=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts \
+          --jq '.artifacts[] | select(.name=="$ARTIFACT_NAME") | .id')
+        if [ -z "$ART_ID" ]; then
+          echo "Artifact $ARTIFACT_NAME not found in run $RUN_ID" >&2
+          exit 1
       shell: bash
       env:
         PATH: ${{ inputs.path }}
