bump

diff --git a/.github/actions/wf_specific/prevalidation/enroll_eabprofile/action.yml b/.github/actions/wf_specific/prevalidation/enroll_eabprofile/action.yml
--- a/.github/actions/wf_specific/prevalidation/enroll_eabprofile/action.yml
+++ b/.github/actions/wf_specific/prevalidation/enroll_eabprofile/action.yml
@@ -26,7 +26,7 @@ runs:
   - name: "EAB - 00b - Enroll lego including prevalidated domain (to succeed)"
     run: |
       sudo rm -rf lego/*
-      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego:v4.35.2--tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -eab --kid keyid_00 --hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d lego.acme -d lego01.acme.local --http run
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego:v4.35.2 --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -eab --kid keyid_00 --hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d lego.acme -d lego01.acme.local --http run
     shell: bash
 
   - name: "EAB - 00c - Enroll lego including prevalidated ip (to succeed)"
@@ -47,19 +47,32 @@ runs:
       docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego:v4.35.2 --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -eab --kid keyid_00 --hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d 10.0.0.1 --http run
     shell: bash
 
+  - name: "EAB - 00f - Enroll lego with with invalid fqdn but preauthorized domain and ip (to fail)"
+    id: legofail00-01
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego:v4.35.2 --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -eab --kid keyid_00 --hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d lego.acme1 -d lego01.acme.local -d 10.0.0.1 --http run
+    shell: bash
 
+  - name: "EAB - 00f - check  result "
+    if: steps.legofail00-01.outcome != 'failure'
+    run: |
+      echo "legofail outcome is ${{steps.legofail00-01.outcome }}"
+      exit 1
+    shell: bash
 
-#  - name: "EAB - 02 - Enroll lego with a not allowed fqdn in kid.json (to fail)"
-#    id: legofail01
-#    continue-on-error: true
-#    run: |
-#      sudo rm -rf lego/*
-#      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network rm-rf.ninja goacme/lego:v4.35.2 --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" --key-type=rsa2048 --eab --kid keyid_02 --hmac dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM -d lego.rm-rf.ninja --http run
-#    shell: bash
+  - name: "EAB - 00g - Enroll lego with with invalid ip but preauthorized domain and ip (to fail)"
+    id: legofail00-02
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego:v4.35.2 --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" -eab --kid keyid_00 --hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d 192.168.1.1 -d lego01.acme.local -d 10.0.0.1 --http run
+    shell: bash
 
-#  - name: "EAB - 04a - check  result "
-#    if: steps.legofail01.outcome != 'failure'
-#    run: |
-#      echo "legofail outcome is ${{steps.legofail01.outcome }}"
-#      exit 1
-#    shell: bash
+  - name: "EAB - 00g - check  result "
+    if: steps.legofail00-02.outcome != 'failure'
+    run: |
+      echo "legofail outcome is ${{steps.legofail00-02.outcome }}"
+      exit 1
+    shell: bash
