[ci] profiles_check_disable option test

diff --git a/.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile/action.yml b/.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile/action.yml
--- a/.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile/action.yml
+++ b/.github/actions/wf_specific/xca_ca_handler/enroll_eab_acmeprofile/action.yml
@@ -49,6 +49,54 @@ runs:
       sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Server Authentication, TLS Web Client Authentication"
     shell: bash
 
+  - name: "EAB - 02c - Enroll lego with unknown profile when profiles_check_disable is set"
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego run --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" --eab --eab.kid keyid_04 --eab.hmac YW5kX2hlcmVfaXNfYW5vdGhlcl92ZXJ5X2xvbmdfbWFja19obWFjX2tleV90b19jaGVja19pZl9jaGFuZ2VzX2FmZmVjdF9pbW1lZGF0ZWx5 -d lego.acme --http --profile unknown
+      sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  lego/certificates/lego.acme.crt
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext keyUsage | grep "Digital Signature, Non Repudiation, Key Encipherment, Key Agreement"
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Server Authentication, TLS Web Client Authentication"
+    shell: bash
+
+  - name: "EAB - 02d - Enroll lego with unknown profile on keyid_00 after disable kid (isolation)"
+    id: legofail01b
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego run --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" --eab --eab.kid keyid_00 --eab.hmac V2VfbmVlZF9hbm90aGVyX3ZlcnkfX2xvbmdfaG1hY190b19jaGVja19lYWJfZm9yX2tleWlkXzAwX2FzX2xlZ29fZW5mb3JjZXNfYW5faG1hY19sb25nZXJfdGhhbl8yNTZfYml0cw -d lego.acme --http --profile unknown
+    shell: bash
+
+  - name: "EAB - 02d - check result"
+    if: steps.legofail01b.outcome != 'failure'
+    run: |
+      echo "legofail outcome is ${{steps.legofail01b.outcome }}"
+      exit 1
+    shell: bash
+
+  - name: "EAB - 02e - Enroll lego with unknown profile when disable and template_name list (to fail)"
+    id: legofail04
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego run --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" --eab --eab.kid keyid_05 --eab.hmac a2V5aWRfMDVfaG1hY19rZXlfd2hpY2hfaXNfbG9uZ2VyX3RoYW5fMjU2X2JpdHNfZm9yX3Byb2ZpbGVfY2hlY2tfZGlzYWJsZV9jaXh4 -d lego.acme --http --profile unknown
+    shell: bash
+
+  - name: "EAB - 02e - check result"
+    if: steps.legofail04.outcome != 'failure'
+    run: |
+      echo "legofail outcome is ${{steps.legofail04.outcome }}"
+      exit 1
+    shell: bash
+
+  - name: "EAB - 02f - Enroll lego with allowed profile when disable and template_name list"
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego run --tls-skip-verify -s https://acme-srv -a --email "lego@example.com" --eab --eab.kid keyid_05 --eab.hmac a2V5aWRfMDVfaG1hY19rZXlfd2hpY2hfaXNfbG9uZ2VyX3RoYW5fMjU2X2JpdHNfZm9yX3Byb2ZpbGVfY2hlY2tfZGlzYWJsZV9jaXh4 -d lego.acme --http --profile acme
+      sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  lego/certificates/lego.acme.crt
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext keyUsage | grep "Digital Signature, Non Repudiation, Key Encipherment, Key Agreement"
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Server Authentication, TLS Web Client Authentication"
+    shell: bash
+
   - name: "EAB - 03 - Enroll lego with a template_name/ca_name taken from kid.json"
     run: |
       sudo rm -rf lego/*
