bump

diff --git a/.github/actions/wf_specific/prevalidation/enroll/action.yml b/.github/actions/wf_specific/prevalidation/enroll/action.yml
--- a/.github/actions/wf_specific/prevalidation/enroll/action.yml
+++ b/.github/actions/wf_specific/prevalidation/enroll/action.yml
@@ -77,6 +77,26 @@ runs:
       env:
         DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
 
+    - name: "Enroll lego with both ip and domain prevalidation"
+      if: ${{ inputs.PREVALIDATED == 'both' }}
+      id: lego-both-fail01
+      continue-on-error: true
+      run: |
+        sudo rm -rf lego/*
+        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network $NAME_SPACE goacme/lego --tls-skip-verify -s https://$ACME_SERVER -a --email "lego@example.com" -d lego-01.acme -d lego-01.foo.local -d 172.0.0.2 -d 10.0.0.1 --http run
+      shell: bash
+      env:
+        ACME_SERVER: ${{ inputs.ACME_SERVER }}
+        CA_PATH: ${{ inputs.CA_PATH }}
+        NAME_SPACE: ${{ inputs.NAME_SPACE }}
+
+    - name: "Check  result "
+      if: ${{ (inputs.PREVALIDATED == 'both') && steps.lego-both-fail01.outcome != 'failure' }}
+      run: |
+        echo "lego-both-fail01 outcome is ${{steps.lego-both-fail01.outcome }}"
+        exit 1
+      shell: bash
+
     - name: "Enroll lego with domain prevalidation and resolvable domain"
       if: ${{ inputs.PREVALIDATED == 'domain' || inputs.PREVALIDATED == 'both' }}
       run: |
