bump

diff --git a/.github/actions/wf_specific/prevalidation/enroll/action.yml b/.github/actions/wf_specific/prevalidation/enroll/action.yml
--- a/.github/actions/wf_specific/prevalidation/enroll/action.yml
+++ b/.github/actions/wf_specific/prevalidation/enroll/action.yml
@@ -77,7 +77,7 @@ runs:
       env:
         DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
 
-    - name: "Enroll lego with both ip and domain prevalidation"
+    - name: "Enroll lego with both ip and domain prevalidation (to fail)"
       if: ${{ inputs.PREVALIDATED == 'both' }}
       id: lego-both-fail01
       continue-on-error: true
@@ -149,7 +149,27 @@ runs:
       env:
         DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
 
-    - name: "Enroll lego with both ip"
+    - name: "Enroll lego with both ip and domain prevalidation (to fail)"
+      if: ${{ inputs.PREVALIDATED == 'both' || inputs.PREVALIDATED == 'domain' }}
+      id: lego-domain-fail01
+      continue-on-error: true
+      run: |
+        sudo rm -rf lego/*
+        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network $NAME_SPACE goacme/lego --tls-skip-verify -s https://$ACME_SERVER -a --email "lego@example.com" -d lego-04.acme -d lego-04.foo.local --http run
+      shell: bash
+      env:
+        ACME_SERVER: ${{ inputs.ACME_SERVER }}
+        CA_PATH: ${{ inputs.CA_PATH }}
+        NAME_SPACE: ${{ inputs.NAME_SPACE }}
+
+    - name: "Check  result "
+      if: ${{ (inputs.PREVALIDATED == 'both' || inputs.PREVALIDATED == 'domain') && steps.lego-domain-fail01.outcome != 'failure' }}
+      run: |
+        echo "lego-domain-fail01 outcome is ${{steps.lego-domain-fail01.outcome }}"
+        exit 1
+      shell: bash
+
+    - name: "Enroll lego with ip"
       if: ${{ inputs.PREVALIDATED == 'both' || inputs.PREVALIDATED == 'ip' }}
       run: |
         sudo rm -rf lego/*
@@ -174,3 +194,23 @@ runs:
       shell: bash
       env:
         DEPLOYMENT_TYPE: ${{ inputs.DEPLOYMENT_TYPE }}
+
+    - name: "Enroll lego with both ip and domain prevalidation (to fail)"
+      if: ${{ inputs.PREVALIDATED == 'both' || inputs.PREVALIDATED == 'ip' }}
+      id: lego-ip-fail01
+      continue-on-error: true
+      run: |
+        sudo rm -rf lego/*
+        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network $NAME_SPACE goacme/lego --tls-skip-verify -s https://$ACME_SERVER -a --email "lego@example.com" -d 172.0.0.2 -d 10.0.0.1 --http run
+      shell: bash
+      env:
+        ACME_SERVER: ${{ inputs.ACME_SERVER }}
+        CA_PATH: ${{ inputs.CA_PATH }}
+        NAME_SPACE: ${{ inputs.NAME_SPACE }}
+
+    - name: "Check  result "
+      if: ${{ (inputs.PREVALIDATED == 'both' || inputs.PREVALIDATED == 'ip') && steps.lego-ip-fail01.outcome != 'failure' }}
+      run: |
+        echo "lego-ip-fail01 outcome is ${{steps.lego-ip-fail01.outcome }}"
+        exit 1
+      shell: bash
