[wf] extended header_info tests

diff --git a/.github/workflows/ca_handler_tests_certifier.yml b/.github/workflows/ca_handler_tests_certifier.yml
--- a/.github/workflows/ca_handler_tests_certifier.yml
+++ b/.github/workflows/ca_handler_tests_certifier.yml
@@ -505,6 +505,33 @@ jobs:
         sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
         sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "Code Signing"
 
+    - name: "EAB - 06 - Enroll acme with not allowed headerinfo-field (should fail)"
+      id: acmefail03
+      continue-on-error: true
+      run: |
+        sudo rm -rf acme-sh/*
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --register-account --server http://acme-srv --accountemail 'acme-sh@example.com' --eab-kid keyid_02 --eab-hmac-key dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM --debug 3
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv --useragent profile_id=101 -d acme-sh.acme --standalone --debug 3 --output-insecure
+
+    - name: "EAB - 06 - check  result "
+      if: steps.acmefail03.outcome != 'failure'
+      run: |
+        echo "acmefail outcome is ${{steps.acmefail03.outcome }}"
+        exit 1
+
+    - name: "EAB - 06 - Enroll lego with not allowed headerinfo-field (should fail)"
+      id: legofail03
+      continue-on-error: true
+      run: |
+        sudo rm -rf lego/*
+        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego -s http://acme-srv -a --email "lego@example.com" --eab --kid keyid_02 --hmac dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM --user-agent profile_id=101 -d lego.acme --http run
+
+    - name: "EAB - 06 - check  result "
+      if: steps.legofail03.outcome != 'failure'
+      run: |
+        echo "legofail outcome is ${{steps.legofail03.outcome }}"
+        exit 1
+
     - name: "[ * ] collecting test logs"
       if: ${{ failure() }}
       run: |
@@ -1023,6 +1050,33 @@ jobs:
         sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  lego/certificates/lego.acme.crt
         sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
         sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "Code Signing"
+
+    - name: "EAB - 06 - Enroll acme with not allowed headerinfo-field (should fail)"
+      id: acmefail03
+      continue-on-error: true
+      run: |
+        sudo rm -rf acme-sh/*
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --register-account --server http://acme-srv --accountemail 'acme-sh@example.com' --eab-kid keyid_02 --eab-hmac-key dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM --debug 3
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv --useragent profile_id=101 -d acme-sh.acme --standalone --debug 3 --output-insecure
+
+    - name: "EAB - 06 - check  result "
+      if: steps.acmefail03.outcome != 'failure'
+      run: |
+        echo "acmefail outcome is ${{steps.acmefail03.outcome }}"
+        exit 1
+
+    - name: "EAB - 06 - Enroll lego with not allowed headerinfo-field (should fail)"
+      id: legofail03
+      continue-on-error: true
+      run: |
+        sudo rm -rf lego/*
+        docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego -s http://acme-srv -a --email "lego@example.com" --eab --kid keyid_02 --hmac dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM --user-agent profile_id=101 -d lego.acme --http run
+
+    - name: "EAB - 06 - check  result "
+      if: steps.legofail03.outcome != 'failure'
+      run: |
+        echo "legofail outcome is ${{steps.legofail03.outcome }}"
+        exit 1
 
     - name: "[ * ] collecting test logs"
       if: ${{ failure() }}
