bump

diff --git a/.github/workflows/ca_handler_tests_cmp.yml b/.github/workflows/ca_handler_tests_cmp.yml
--- a/.github/workflows/ca_handler_tests_cmp.yml
+++ b/.github/workflows/ca_handler_tests_cmp.yml
@@ -546,3 +546,255 @@ jobs:
         with:
           name: test-rpm-rh${{ matrix.rhversion }}-${{ matrix.execscript }}.tar.gz
           path: ${{ github.workspace }}/artifact/upload/
+
+  # ---------------------------------------------------------
+  # Test DEB downloaded from the producer run
+  # ---------------------------------------------------------
+  test-deb:
+    needs: guard
+    runs-on: ubuntu-latest
+    if: github.repository == 'grindsa/acme2certifier'
+    strategy:
+      fail-fast: false
+      max-parallel: 1
+      matrix:
+        websrv: ['apache2', 'nginx']
+        execscript: ['deb_tester.sh', 'django_tester.sh']
+
+    steps:
+      - name: "checkout GIT"
+        uses: actions/checkout@v4
+
+      - name: "Parse CMP configuration"
+        uses: ./.github/actions/parse-json-secret
+        with:
+          json_secret: ${{ secrets.CMP_CFG }}
+          uppercase: 'true'
+
+      - name: "Parse SSH tunnel configuration"
+        uses: ./.github/actions/parse-json-secret
+        with:
+          json_secret: ${{ secrets.SSH_TUNNEL_CFG }}
+          uppercase: 'true'
+
+      - name: "Get runner ip"
+        run: |
+          echo RUNNER_IP=$(ip addr show eth0 | grep -i "inet " | cut -d ' ' -f 6 | cut -d '/' -f 1) >> $GITHUB_ENV
+          echo RUNNER_PATH=$(pwd | sed 's_/_\\/_g') >> $GITHUB_ENV
+
+      - run: echo "runner IP is $RUNNER_IP"
+        env:
+          RUNNER_IP: ${{ env.RUNNER_IP }}
+
+      - name: "Prepare Ubuntu environment"
+        if: matrix.execscript == 'deb_tester.sh'
+        uses: ./.github/actions/deb_prep
+        with:
+          DEB_BUILD: false
+
+      - name: "Prepare Ubuntu environment"
+        if: matrix.execscript == 'django_tester.sh'
+        uses: ./.github/actions/deb_prep
+        with:
+          DEB_BUILD: false
+          DJANGO_DB: psql
+
+      - name: "Download DEB artifact by name from build run"
+        uses: ./.github/actions/download_artifact
+        with:
+          RUN_ID: ${{ inputs.run_id }}
+          ARTIFACT_NAME: acme2certifier-${{ inputs.run_id }}-1_all.deb
+          DESTINATION_PATH: data/
+          TOKEN: ${{ secrets.GH_WF_TOKEN }}
+          REPO: ${{ github.repository }}
+
+      - name: "Create ssh environment on ramdisk"
+        run: |
+          sudo mkdir -p /tmp/rd
+          sudo mount -t tmpfs -o size=5M none /tmp/rd
+          sudo echo "$SSH_KEY" > /tmp/rd/ak.tmp
+          sudo chmod 600 /tmp/rd/ak.tmp
+          sudo echo "$KNOWN_HOSTS" > /tmp/rd/known_hosts
+        env:
+          SSH_KEY: ${{ env.SSH_KEY }}
+          KNOWN_HOSTS: ${{ env.SSH_KNOWN_HOSTS }}
+
+      - name: "Setup ssh forwarder"
+        run: |
+            docker run -d --rm --network acme --name=ssh-forwarder.acme  -e "MAPPINGS=8086:$CMP_HOST:8086" -e "SSH_HOST=$SSH_HOST" -e "SSH_PORT=$SSH_PORT" -e "SSH_USER=$SSH_USER" -p 443:443 -p 445:445 -p 88:88 -v "/tmp/rd/ak.tmp:/ssh_key:ro" davidlor/ssh-port-forward-client:dev
+        env:
+          SSH_USER: ${{ env.SSH_USER }}
+          SSH_HOST: ${{ env.SSH_HOST}}
+          SSH_PORT: ${{ env.SSH_PORT }}
+          CMP_HOST: ${{ env.CMP_HOST }}
+
+      - name: "Sleep for 5s"
+        uses: juliangruber/sleep-action@v2.0.3
+        with:
+          time: 5s
+
+      - name: "Setup a2c with cmp_ca_handler"
+        run: |
+          sudo mkdir data/volume/acme_ca
+          sudo cp test/ca/root-ca-cert.pem data/volume/acme_ca
+          sudo cp test/ca/sub-ca-cert.pem data/volume/acme_ca
+          sudo touch data/volume/acme_ca/ca_bundle.pem
+          sudo touch data/volume/acme_ca/ra_cert.pem
+          sudo touch data/volume/acme_ca/ra_key.pem
+          sudo chmod 777 data/volume/acme_ca/*.pem
+          sudo echo "$CMP_TRUSTED" > data/volume/acme_ca/ca_bundle.pem
+          sudo echo "$CMP_RA_CERT" > data/volume/acme_ca/ra_cert.pem
+          sudo echo "$CMP_RA_KEY" >  data/volume/acme_ca/ra_key.pem
+          sudo touch data/volume/acme_srv.cfg
+          sudo chmod 777 data/volume/acme_srv.cfg
+          sudo head -n -8 .github/openssl_ca_handler.py_acme_srv_default_handler.cfg > data/volume/acme_srv.cfg
+          sudo echo "handler_file: /opt/acme2certifier/examples/ca_handler/cmp_ca_handler.py" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_path: pkix/" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_ignore_keyusage: True" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_msg_timeout: 3" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_total_timeout: 5" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_server: ssh-forwarder.acme:8086" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_cert: /opt/acme2certifier/volume/acme_ca/ra_cert.pem" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_key: /opt/acme2certifier/volume/acme_ca/ra_key.pem" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_trusted: /opt/acme2certifier/volume/acme_ca/ca_bundle.pem" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_recipient: $CMP_RECIPIENT" >> data/volume/acme_srv.cfg
+          sudo echo "allowed_domainlist: [\"bar.local\", \"*.acme\"]" >> data/volume/acme_srv.cfg
+        env:
+          RUNNER_IP: ${{ env.RUNNER_IP }}
+          CMP_RECIPIENT: ${{ env.CMP_RECIPIENT }}
+          CMP_RA_KEY: ${{ env.CMP_RA_KEY }}
+          CMP_RA_CERT: ${{ env.CMP_RA_CERT }}
+          CMP_TRUSTED: ${{ env.CMP_TRUSTED }}
+
+
+      - name: "Execute install scipt"
+        run: |
+          docker exec acme-srv bash /tmp/acme2certifier/$EXECSCRIPT install $WEBSRV
+        env:
+          WEBSRV: ${{ matrix.websrv }}
+          EXECSCRIPT: ${{ matrix.execscript }}
+
+      - name: "Sleep for 10s"
+        uses: juliangruber/sleep-action@v2.0.3
+        with:
+          time: 10s
+
+      - name: "Test http://acme-srv/directory is accessible"
+        run: docker run -i --rm --network acme curlimages/curl -f http://acme-srv/directory
+
+      - name: "Test if https://acme-srv/directory is accessible"
+        run: docker run -i --rm --network acme curlimages/curl --insecure -f https://acme-srv/directory
+
+      - name: "Enroll acme.sh"
+        run: |
+          docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv --accountemail 'acme-sh@example.com' -d acme-sh.acme --alpn --standalone --debug 3 --output-insecure --force
+          awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "cert-" c ".pem"}' < acme-sh/acme-sh.acme_ecc/ca.cer
+          openssl verify -CAfile cert-2.pem -untrusted cert-1.pem acme-sh/acme-sh.acme_ecc/acme-sh.acme.cer
+
+      - name: "Allowed domainlist feature - Enroll lego (fail)"
+        continue-on-error: true
+        id: legofail01
+        run: |
+          docker run -i --rm -v $PWD/lego:/.lego/ --name lego --network acme goacme/lego -s  https://acme-srv --tls-skip-verify -a --email "lego@example.com" -d lego --tls run
+
+      - name: "Allowed domainlist feature - check  result "
+        if: ${{ steps.legofail01.outcome != 'failure' }}
+        run: |
+          echo "legofail outcome is ${{steps.legofail01.outcome }}"
+          exit 1
+
+      - name: "Setup a2c with cmp_ca_handler"
+        run: |
+          sudo mkdir -p data/volume/acme_ca
+          sudo cp test/ca/root-ca-cert.pem data/volume/acme_ca
+          sudo cp test/ca/sub-ca-cert.pem data/volume/acme_ca
+          sudo touch data/volume/acme_ca/ca_bundle.pem
+          sudo touch data/volume/acme_ca/ra_cert.pem
+          sudo chmod 777 data/volume/acme_ca/*.pem
+          sudo echo "$CMP_TRUSTED" > data/volume/acme_ca/ca_bundle.pem
+          sudo echo "$CMP_RA_CERT" > data/volume/acme_ca/ra_cert.pem
+          sudo touch data/volume/acme_srv.cfg
+          sudo chmod 777 data/volume/acme_srv.cfg
+          sudo head -n -8 .github/openssl_ca_handler.py_acme_srv_default_handler.cfg > data/volume/acme_srv.cfg
+          sudo echo "handler_file: /opt/acme2certifier/examples/ca_handler/cmp_ca_handler.py" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_path: pkix/" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_ignore_keyusage: True" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_msg_timeout: 3" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_total_timeout: 5" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_server: ssh-forwarder.acme:8086" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_cert: /opt/acme2certifier/volume/acme_ca/ra_cert.pem" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_trusted: /opt/acme2certifier/volume/acme_ca/ca_bundle.pem" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_recipient: $CMP_RECIPIENT" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_ref: $CMP_REF" >> data/volume/acme_srv.cfg
+          sudo echo "cmp_secret: $CMP_SECRET" >> data/volume/acme_srv.cfg
+          sudo echo "allowed_domainlist: [\"bar.local\", \"*.acme\"]" >> data/volume/acme_srv.cfg
+        env:
+          RUNNER_IP: ${{ env.RUNNER_IP }}
+          CMP_RECIPIENT: ${{ env.CMP_RECIPIENT }}
+          CMP_RA_CERT: ${{ env.CMP_RA_CERT }}
+          CMP_TRUSTED: ${{ env.CMP_TRUSTED }}
+          CMP_REF: ${{ env.CMP_REF }}
+          CMP_SECRET: ${{ env.CMP_SECRET }}
+
+      - name: "Reconfigure a2c "
+        run: |
+          docker exec acme-srv bash /tmp/acme2certifier/$EXECSRIPT restart $WEBSRV
+        env:
+          WEBSRV: ${{ matrix.websrv }}
+          EXECSRIPT: ${{ matrix.execscript }}
+
+      - name: "Sleep for 10s"
+        uses: juliangruber/sleep-action@v2.0.3
+        with:
+          time: 10s
+
+      - name: "Test http://acme-srv/directory is accessible"
+        run: docker run -i --rm --network acme curlimages/curl -f http://acme-srv/directory
+
+      - name: "Test if https://acme-srv/directory is accessible"
+        run: docker run -i --rm --network acme curlimages/curl --insecure -f https://acme-srv/directory
+
+      - name: "Enroll acme.sh"
+        run: |
+          docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv --accountemail 'acme-sh@example.com' -d acme-sh.acme --alpn --standalone --debug 3 --output-insecure --force
+          awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "cert-" c ".pem"}' < acme-sh/acme-sh.acme_ecc/ca.cer
+          openssl verify -CAfile cert-2.pem -untrusted cert-1.pem acme-sh/acme-sh.acme_ecc/acme-sh.acme.cer
+
+      - name: "Allowed domainlist feature - Enroll lego (fail)"
+        continue-on-error: true
+        id: legofail02
+        run: |
+          docker run -i --rm -v $PWD/lego:/.lego/ --name lego --network acme goacme/lego -s  https://acme-srv --tls-skip-verify -a --email "lego@example.com" -d lego --tls run
+
+      - name: "Allowed domainlist feature - check  result "
+        if: ${{ steps.legofail02.outcome != 'failure' }}
+        run: |
+          echo "legofail outcome is ${{steps.legofail02.outcome }}"
+          exit 1
+
+      - name: "Sleep for 10s"
+        uses: juliangruber/sleep-action@v2.0.3
+        with:
+          time: 10s
+
+      - name: "[ * ] collecting test logs"
+        if: ${{ failure() }}
+        run: |
+          mkdir -p ${{ github.workspace }}/artifact/upload
+          docker exec acme-srv tar cvfz /tmp/acme2certifier/a2c.tgz /var/www/acme2certifier
+          sudo cp -rp data/ ${{ github.workspace }}/artifact/data/
+          sudo rm ${{ github.workspace }}/artifact/data/*.deb
+          if [ ${{ matrix.websrv }} == "apache2" ]; then
+            docker exec acme-srv cat /var/log/apache2/error.log > ${{ github.workspace }}/artifact/acme-srv.log
+          else
+            docker exec acme-srv cat /var/log/nginx/error.log > ${{ github.workspace }}/artifact/acme-srv.log
+          fi
+          docker exec acme-srv cat /var/log/syslog > ${{ github.workspace }}/artifact/syslog
+          sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz data acme-srv.log syslog
+
+      - name: "[ * ] uploading artificates"
+        uses: actions/upload-artifact@v4
+        if: ${{ failure() }}
+        with:
+          name: test-deb-${{ matrix.websrv }}-${{ matrix.execscript }}.tar.gz
+          path: ${{ github.workspace }}/artifact/upload/
