[wf] updated eab worflow containing kid check

diff --git a/.github/workflows/eab-test.yml b/.github/workflows/eab-test.yml
--- a/.github/workflows/eab-test.yml
+++ b/.github/workflows/eab-test.yml
@@ -50,9 +50,14 @@ jobs:
 
     - name: "Restart a2c"
       run: |
+        sudo mkdir -p examples/Docker/data/acme_ca/certs
+        sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem examples/Docker/data/acme_ca/
+        sudo cp examples/eab_handler/key_file.json examples/Docker/data/acme_ca
+        sudo cp .github/openssl_ca_handler.py_acme_srv_choosen_handler.cfg examples/Docker/data/acme_srv.cfg
+        sudo chmod 777 examples/Docker/data/acme_srv.cfg
         sudo echo -e "\n\n[EABhandler]" >> examples/Docker/data/acme_srv.cfg
         sudo echo "eab_handler_file: /var/www/acme2certifier/examples/eab_handler/json_handler.py" >> examples/Docker/data/acme_srv.cfg
-        sudo echo "key_file: examples/eab_handler/key_file.json" >> examples/Docker/data/acme_srv.cfg
+        sudo echo "key_file: /var/www/acme2certifier/volume/acme_ca/key_file.json" >> examples/Docker/data/acme_srv.cfg
         cd examples/Docker/
         docker-compose restart
 
@@ -127,6 +132,25 @@ jobs:
         docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv -d acme-sh.acme --standalone --debug 3 --output-insecure
         openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  acme-sh/acme-sh.acme_ecc/acme-sh.acme.cer
 
+    - name: "Activate eab_check and rename kid"
+      run: |
+        sudo echo "eab_kid_check: True" >> examples/Docker/data/acme_srv.cfg
+        sudo sed -i "s/keyid_02/keyid_12/g" examples/Docker/data/acme_ca/key_file.json
+        cd examples/Docker/
+        docker-compose restart
+
+    - name: "Enroll acme.sh with unknown kid - should fail"
+      id: acmekidfail
+      continue-on-error: true
+      run: |
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv -d acme-sh.acme --standalone --force --debug 3 --output-insecure
+
+    - name: "Check result "
+      if: steps.acmekidfail.outcome != 'failure'
+      run: |
+        echo "certbot outcome is ${{steps.acmekidfail.outcome }}"
+        exit 1
+
     - name: "[ * ] collecting test logs"
       if: ${{ failure() }}
       run: |
@@ -187,15 +211,14 @@ jobs:
     - name: "Enable EABhandler"
       if: matrix.execscript == 'rpm_tester.sh'
       run: |
+        sudo mkdir -p data/acme_ca/certs/
+        sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/acme_ca/
+        sudo cp examples/eab_handler/key_file.json data/acme_ca/
+        sudo cp .github/openssl_ca_handler.py_acme_srv_choosen_handler.cfg data/acme_srv.cfg
+        sudo chmod 777 data/acme_srv.cfg
         sudo echo -e "\n\n[EABhandler]" >> data/acme_srv.cfg
         sudo echo "eab_handler_file: /opt/acme2certifier/examples/eab_handler/json_handler.py" >> data/acme_srv.cfg
-        sudo echo "key_file: /opt/acme2certifier/examples/eab_handler/key_file.json" >> data/acme_srv.cfg
-      env:
-        NCM_API_HOST: ${{ secrets.NCM_API_HOST }}
-        NCM_API_USER: ${{ secrets.NCM_API_USER }}
-        NCM_API_PASSWORD: ${{ secrets.NCM_API_PASSWORD }}
-        NCM_CA_NAME: ${{ secrets.NCM_CA_NAME }}
-        NCM_CA_BUNDLE: ${{ secrets.NCM_CA_BUNDLE }}
+        sudo echo "key_file: /opt/acme2certifier/volume/acme_ca/key_file.json" >> data/acme_srv.cfg
 
     - name: "Prepare acme_srv.cfg with certifier_ca_handler"
       if: matrix.execscript == 'django_tester.sh'
@@ -215,9 +238,14 @@ jobs:
     - name: "Enable EABhandler"
       if: matrix.execscript == 'django_tester.sh'
       run: |
+        sudo mkdir -p data/volume/acme_ca/certs
+        sudo cp test/ca/sub-ca-key.pem test/ca/sub-ca-crl.pem test/ca/sub-ca-cert.pem test/ca/root-ca-cert.pem data/volume/acme_ca/
+        sudo cp examples/eab_handler/key_file.json data/volume/acme_ca
+        sudo cp .github/openssl_ca_handler.py_acme_srv_choosen_handler.cfg data/volume/acme_srv.cfg
+        sudo chmod 777 data/volume/acme_srv.cfg
         sudo echo -e "\n\n[EABhandler]" >> data/volume/acme_srv.cfg
         sudo echo "eab_handler_file: /opt/acme2certifier/examples/eab_handler/json_handler.py" >>data/volume/acme_srv.cfg
-        sudo echo "key_file: /opt/acme2certifier/examples/eab_handler/key_file.json" >> data/volume/acme_srv.cfg
+        sudo echo "key_file: /opt/acme2certifier/volume/acme_ca/key_file.json" >> data/volume/acme_srv.cfg
 
     - name: "Execute install scipt"
       run: |
@@ -295,6 +323,41 @@ jobs:
       run: |
         docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv -d acme-sh.acme --standalone --debug 3 --output-insecure
         openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  acme-sh/acme-sh.acme_ecc/acme-sh.acme.cer
+
+    - name: "Activate eab_check and rename kid"
+      if: matrix.execscript == 'rpm_tester.sh'
+      run: |
+        sudo echo "eab_kid_check: True" >> data/acme_srv.cfg
+        sudo sed -i "s/keyid_02/keyid_12/g" data/acme_ca/key_file.json
+
+    - name: "Activate eab_check and rename kid"
+      if: matrix.execscript == 'django_tester.sh'
+      run: |
+        sudo echo "eab_kid_check: True" >> data/volume/acme_srv.cfg
+        sudo sed -i "s/keyid_02/keyid_12/g" data/volume/acme_ca/key_file.json
+
+    - name: "Reconfigure a2c"
+      run: |
+        docker exec acme-srv sh /tmp/acme2certifier/$EXEC_SCRIPT  restart
+      env:
+        EXEC_SCRIPT: ${{ matrix.execscript }}
+
+    - name: "Sleep for 5s"
+      uses: juliangruber/sleep-action@v2.0.3
+      with:
+        time: 5s
+
+    - name: "Enroll acme.sh with unknown kid - should fail"
+      id: acmekidfail
+      continue-on-error: true
+      run: |
+        docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv -d acme-sh.acme --standalone --force --debug 3 --output-insecure
+
+    - name: "Check result "
+      if: steps.acmekidfail.outcome != 'failure'
+      run: |
+        echo "certbot outcome is ${{steps.acmekidfail.outcome }}"
+        exit 1
 
     - name: "[ * ] collecting test logs"
       if: ${{ failure() }}
